name: 'CodeScan Scanner'
description: 'Use the CodeScan Scanner in your workflows to track bugs, code smells and vulnerabilities in Salesforce languages.'
author: 'CodeScan Enterprises LLC'
branding:
  icon: code
  color: 'blue'
inputs:
  organization:
    required: true
    description: 'CodeScan Organization Key'
  projectKey:
    required: true
    description: 'CodeScan Project Key'
  login:
    required: true
    description: 'CodeScan Login Key'
  codeScanUrl:
    required: false
    description: 'CodeScanCloud endpoint for your project'
    default: 'https://app.codescan.io/'
  pollingTimeoutSec:
    required: false
    description: 'This task will poll CodeScanCloud until the analysis is completed, or until the timeout is reached'
    default: '900'
  scanChangedFilesOnly:
    required: false
    description: 'The flag to indicate that PR scans should only analyze added, changed or modified files in the PR'
    default: 'false'
  generateSarifFile:
    required: false
    description: 'The flag to indicate that SARIF file should be generated on server side'
    default: 'false'
  generateReportFile:
    required: false
    description: 'The flag to indicate that SARIF file should be generated on client side'
    default: 'true'
  failOnRedQualityGate:
    required: false
    description: 'The flag to indicate that pipeline will fail in case of quality gate status failed'
    default: 'false'
  args:
    required: false
    description: 'Additional arguments to the sonarcloud scanner'
runs:
  using: 'node20'
  main: 'dist/index.js'
